[package]
name = "bitter-adblock"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
adblock.workspace = true
url.workspace = true
tracing.workspace = true
