[package]
name = "bitter-net"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
hickory-resolver.workspace = true
reqwest.workspace = true
url.workspace = true
tracing.workspace = true
